### PR TITLE
User/embedded/sft 190 create functions and unit test relating to orion work

### PR DESCRIPTION
**Pull request by badeniran**

### CODE REVIEW

**Comment by badeniran** [comment]
No need to review any files to do with testing

**Comment by badeniran** [comment]
Tried rebasing and it was hell, because apparently there's lots of conflicts between the earlier commits and the later commits, so squashing isn't happening unless one of you can do magic haha

**Review by JessieG123 — COMMENTED** [review]
Squash the commits before Duan and Avneet's commits maybe?

**Comment by badeniran** [comment]
> Squash the commits before Duan and Avneet's commits maybe?

It actually ended up being an issue with my local branch, so it's all g now

**Review by duan-le — APPROVED** [review]

**Review by maaryaahmed — APPROVED** [review]

**Pull request merged**
