### PR TITLE
Send Mppt

### PR DESCRIPTION
**Pull request by bill-luu**
WIP
-Still need to do aliveBit (Do I need to write the alive bit onto bit 7 of each mpptStatus byte? Or is that just already there)
-Should Mppt Size on the protocol be 14 instead of 13? (Last index 8 + short unit 2 + metadata 4)

### CODE REVIEW

**Comment by enochtsang** [comment]
Isn't CI a glorious thing

**Comment by bill-luu** [comment]
Descriptions are pretty sick too

**Comment by enochtsang** [comment]
Uh no, 13 seems right. Last index 8 + 1 for short uint. index 8 and 9 is the last set of info. So size of data is 9 bytes + 4 meta data. 13

**Comment by bill-luu** [comment]
Wait, but if Motor Faults ended at index 8 + uchar(1 byte) + metadata = 13, how does MPPT have index 8 + short uint(2 bytes) + metadata = 13?

**Comment by bill-luu** [comment]
Also, what about the alive bit

**Comment by enochtsang** [comment]
Nvm yea you're right should be 14 for MPPT.

**Comment by bill-luu** [comment]
What about the alive bit

**Comment by bill-luu** [comment]
Ready to review!

**Pull request merged**
